#define ENTITY 1
#define ARCHITECTURE 2
#define T_BEGIN 3
#define END 4
#define IS 5
#define SIGNAL 6
#define PROCESS 7
#define SEMICOLON 8
#define OF 9
#define COLON 10
#define OP_ASSIGN 11
#define TYPE 12
#define IDENTIFIER 13
#define NUMBER 14
